FROM postgres:9.5.3

RUN apt-get update && \
    apt-get install -y vim nano gettext && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN echo "alias ll='ls $LS_OPTIONS -l'" >> /root/.bashrc
ENV POSTGRES_DB=personnelink_dev \
    POSTGRES_PASSWORD=none
    
COPY initdb.d /docker-entrypoint-initdb.d
